<x-app-layout>
<x-slot name="header"><h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200">Editar usuario</h2></x-slot>
<div class="py-12"><div class="max-w-4xl mx-auto sm:px-6 lg:px-8"><div class="bg-white dark:bg-gray-800 shadow-sm rounded-lg p-6 text-gray-900 dark:text-gray-100">
<form action="{{ route('users.update', $user) }}" method="POST">@csrf @method('PUT')
<div class="grid md:grid-cols-2 gap-4"><div><label>Nombre</label><input name="name" value="{{ old('name', $user->name) }}" required class="mt-1 block w-full rounded border-gray-300"></div><div><label>Correo corporativo</label><input type="email" name="email" value="{{ old('email', $user->email) }}" required class="mt-1 block w-full rounded border-gray-300"></div>
<div><label>Perfil</label><select name="profile_id" required class="mt-1 block w-full rounded border-gray-300">@foreach($profiles as $profile)<option value="{{ $profile->id }}" @selected(old('profile_id', $user->profile_id) == $profile->id)>{{ $profile->display_name }}</option>@endforeach</select></div>
<div><label>Estado</label><select name="status" required class="mt-1 block w-full rounded border-gray-300"><option value="pending" @selected(old('status',$user->status)==='pending')>Pendiente de primer acceso</option><option value="active" @selected(old('status',$user->status)==='active')>Activo</option><option value="disabled" @selected(old('status',$user->status)==='disabled')>Deshabilitado</option></select></div></div>
<div class="mt-6"><label class="font-semibold">Centros de costos</label><div class="grid md:grid-cols-2 gap-2 mt-2">@foreach($costCenters as $center)<label class="text-sm"><input type="checkbox" name="cost_centers[]" value="{{ $center->id }}" @checked($user->authorizedCostCenters->contains($center->id))> {{ $center->code }} — {{ $center->name }}</label>@endforeach</div></div>
<div class="mt-6"><label class="font-semibold">Permisos directos</label><div class="grid md:grid-cols-2 gap-2 mt-2">@foreach($permissions as $permission)<label class="text-sm"><input type="checkbox" name="permissions[]" value="{{ $permission->id }}" @checked($user->permissions->contains($permission->id))> {{ $permission->display_name }}</label>@endforeach</div></div>
<div class="mt-6 flex justify-end gap-3"><a href="{{ route('users.index') }}">Cancelar</a><button class="px-4 py-2 bg-gray-800 text-white rounded">Guardar cambios</button></div>
</form></div></div></div>
</x-app-layout>