<x-app-layout :hide-navigation="true">
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-[10px] font-black uppercase tracking-[.25em] text-rose-500">Revisión de alertas</p><h2 class="text-2xl font-black text-gray-900 dark:text-white">Comparativa de posibles duplicados</h2></div><a href="{{ route('admin.device-audit.reimbursements-dashboard', ['section' => 'general', 'range' => $range, 'company' => $companyId, 'cost_center' => $costCenterId]) }}" class="rounded-xl bg-gray-900 px-4 py-2 text-sm font-bold text-white dark:bg-white dark:text-gray-900">Volver al dashboard</a></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-5 px-4 sm:px-6 lg:px-8">
        <form method="GET" class="grid gap-3 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm md:grid-cols-4 dark:border-gray-700 dark:bg-gray-800"><input name="search" value="{{ $search }}" placeholder="RFC, solicitante o centro" class="rounded-xl border-gray-300 text-sm dark:border-gray-600 dark:bg-gray-900 dark:text-white"><select name="company" class="rounded-xl border-gray-300 text-sm dark:border-gray-600 dark:bg-gray-900 dark:text-white"><option value="">Todas las empresas</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected($companyId === $company->id)>{{ $company->name }}</option>@endforeach</select><select name="cost_center" class="rounded-xl border-gray-300 text-sm dark:border-gray-600 dark:bg-gray-900 dark:text-white"><option value="">Todos los centros</option>@foreach($costCenters as $center)<option value="{{ $center->id }}" @selected($costCenterId === $center->id)>{{ $center->code }} · {{ $center->name }}</option>@endforeach</select><button class="rounded-xl bg-rose-600 px-4 py-2 text-sm font-black text-white">Buscar y filtrar</button></form>
        <div class="space-y-5">@forelse($items as $item)<article class="rounded-2xl border border-rose-200 bg-white p-5 shadow-sm dark:border-rose-900 dark:bg-gray-800"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 class="font-black text-gray-900 dark:text-white">{{ $item['rfc'] }} · ${{ number_format($item['amount'], 2) }} · {{ $item['date']->format('d/m/Y') }}</h3><p class="mt-1 text-sm text-rose-700 dark:text-rose-300"><b>Razón:</b> {{ $item['reason'] }}</p><p class="mt-1 text-sm text-gray-500">{{ $item['uuid_note'] }}</p></div><span class="rounded-full bg-rose-100 px-3 py-1 text-sm font-black text-rose-800">{{ $item['count'] }} coincidencias</span></div>
            <form method="POST" action="{{ route('admin.device-audit.reimbursements-dashboard.duplicate-reviews.update') }}" class="mt-4 grid gap-3 rounded-xl border border-gray-200 bg-gray-50 p-4 md:grid-cols-[180px_1fr_auto] dark:border-gray-700 dark:bg-gray-900"><input type="hidden" name="rfc_emisor" value="{{ $item['rfc'] }}"><input type="hidden" name="amount" value="{{ $item['amount'] }}"><input type="hidden" name="invoice_date" value="{{ $item['date']->toDateString() }}">@csrf <select name="status" class="rounded-xl border-gray-300 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"><option value="pending" @selected(($item['review']?->status ?? 'pending') === 'pending')>Pendiente de revisión</option><option value="resolved" @selected(($item['review']?->status ?? '') === 'resolved')>Solucionado</option><option value="blocked" @selected(($item['review']?->status ?? '') === 'blocked')>Bloqueado</option></select><input name="note" value="{{ $item['review']?->note }}" maxlength="2000" placeholder="Nota de la solución o bloqueo" class="rounded-xl border-gray-300 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"><button class="rounded-xl bg-gray-900 px-4 py-2 text-sm font-black text-white dark:bg-white dark:text-gray-900">Guardar</button></form>@if($item['review'])<p class="mt-2 text-xs text-gray-500">Última actualización: {{ $item['review']->reviewed_at?->format('d/m/Y H:i') }} por {{ $item['review']->reviewedBy?->name ?: 'Administrador' }}</p>@endif
            <div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500 dark:bg-gray-900"><tr><th class="px-4 py-3">Solicitud</th><th class="px-4 py-3">Solicitante</th><th class="px-4 py-3">Centro</th><th class="px-4 py-3">UUID fiscal</th><th class="px-4 py-3">Estatus</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-700">@foreach($item['records'] as $record)<tr><td class="px-4 py-3"><a href="{{ route('reimbursements.show', $record['id']) }}" class="font-mono font-bold text-indigo-600 hover:underline">{{ $record['folio'] ?: '#' . $record['id'] }}</a></td><td class="px-4 py-3">{{ $record['user'] }}</td><td class="px-4 py-3">{{ $record['center'] }}</td><td class="px-4 py-3 font-mono text-xs">{{ $record['uuid'] }}</td><td class="px-4 py-3">{{ str($record['status'])->replace('_', ' ')->title() }}</td></tr>@endforeach</tbody></table></div>
        </article>@empty <div class="rounded-2xl border border-gray-200 bg-white p-10 text-center text-gray-500 dark:border-gray-700 dark:bg-gray-800">No hay posibles duplicados con los filtros elegidos.</div>@endforelse</div>
        <div>{{ $items->appends(request()->query())->links() }}</div>
    </div></div>
</x-app-layout>
